[sql]
;support two sql,mysql and mssql,choice one
type = mysql
host = 127.0.0.1
port = 3306
user = root
passwd = 111111
db = taobao_spider_db
charset = utf8
hasHadoop=spark

[redis]
host = 127.0.0.1
port = 6379
passwd = 123456

[spark]
; Spark Master地址（虚拟机）
master = spark://192.168.64.101:7077

; Spark Home路径（虚拟机上）
spark_home = /opt/apps/spark

; Python路径（虚拟机上）
python_home = /usr/bin/python3

; HDFS地址
hdfs_namenode = hdfs://192.168.64.101:9000

[hive]
; Hive Metastore地址（虚拟机）
metastore_uris = thrift://192.168.64.101:9083

; Hive数据仓库路径
warehouse_dir = /user/hive/warehouse

[hadoop]
; Hadoop配置目录（虚拟机上）
conf_dir = /opt/apps/hadoop/etc/hadoop